version: '3.8'

services:
  aws-migration:
    build:
      context: .
      dockerfile: Dockerfile
    image: aws-migration-tool:latest
    container_name: aws-migration
    volumes:
      # Mount AWS credentials from host
      - ~/.aws:/root/.aws:ro
      # Mount output directory
      - ./output:/output
    environment:
      - AWS_SDK_LOAD_CONFIG=1
      - AWS_DEFAULT_REGION=us-east-1
    command: python aws_migration.py --report
